# Generated by Django 6.1.1 on 2026-09-11 00:24

import django.db.models.deletion
import pgvector.django.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digestdelivery',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='format_preference',
            field=models.CharField(choices=[('text', 'Texte structuré'), ('audio', 'Audio uniquement'), ('both', 'Texte et Audio')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='deliverychannel',
            name='identifier',
            field=models.CharField(help_text='Chat ID Telegram, numéro WhatsApp, ou Email', max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverychannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='digest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='digestdelivery',
            name='digest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='digests.digest'),
        ),
        migrations.AlterField(
            model_name='digestdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='digest',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='article_embed_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['centroid_embedding'], m=16, name='topic_centroid_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
