# Generated by Django 6.1.1 on 2026-09-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0002_digestdelivery_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('api', 'API')], max_length=20),
        ),
    ]
