# Generated by Django 6.1.1 on 2026-09-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0003_alter_source_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS'), ('reddit', 'Reddit'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('api', 'API')], max_length=20),
        ),
    ]
