# Generated by Django 6.1.1 on 2026-09-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0004_alter_source_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='conversation_state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
