# Generated by Django 6.1.1 on 2026-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0005_userpreference_conversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='timezone',
            field=models.CharField(default='Africa/Douala', help_text='Fuseau horaire (ex: Africa/Douala, Europe/Paris)', max_length=50),
        ),
    ]
