# Generated by Django 6.1.1 on 2026-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0006_userpreference_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, help_text="Date d'envoi de l'alerte breaking news", null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='receive_breaking_alerts',
            field=models.BooleanField(default=True, help_text="Recevoir les alertes d'urgence en temps réel"),
        ),
    ]
